-- Oracle DDL / sample data for DevAreaRev API
-- 화면: devAreaCd 탭, 최종 Rev 조회, Rev 목록 그리드
-- PK: IDENTITY, 업무 키: (DEV_AREA_CD, OWNER_CD, FINAL_REV)

-- ---------------------------------------------------------------------------
-- devAreaCd 탭 마스터
-- API: GET /dev-area-rev/dev-areas  →  devAreaCd, devAreaName
-- ---------------------------------------------------------------------------
CREATE TABLE DEV_AREA (
    DEV_AREA_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    DEV_AREA_CD   VARCHAR2(20)  NOT NULL,
    DEV_AREA_NM   VARCHAR2(100) NOT NULL,
    SORT_ORD      NUMBER(5)     DEFAULT 0 NOT NULL,
    USE_YN        CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT UK_DEV_AREA UNIQUE (DEV_AREA_CD)
);

-- ---------------------------------------------------------------------------
-- devAreaCd + Rev별 Owner Code Rev 정보
-- API: GET /dev-area-rev/final-rev?devAreaCd=  →  MAX(FINAL_REV)
-- API: GET /dev-area-rev?devAreaCd=&finalRev=  →  그리드 row 목록
-- ---------------------------------------------------------------------------
CREATE TABLE DEV_AREA_REV_INF (
    DEV_AREA_REV_INF_ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    DEV_AREA_CD         VARCHAR2(20)  NOT NULL,
    OWNER_CD            VARCHAR2(20)  NOT NULL,
    USAGE_CD            VARCHAR2(20),
    FINAL_REV           NUMBER(10)    NOT NULL,
    REV_STATUS          VARCHAR2(20),
    REV_DESC            VARCHAR2(500),
    CREATE_USER         VARCHAR2(50),
    CREATE_DT           VARCHAR2(19),
    UPDATE_USER         VARCHAR2(50),
    UPDATE_DT           VARCHAR2(19),
    CONSTRAINT UK_DEV_AREA_REV_INF UNIQUE (DEV_AREA_CD, OWNER_CD, FINAL_REV)
);

-- ---------------------------------------------------------------------------
-- devAreaCd 탭 (OWNER_CODE_INF USAGE_CD·i18n과 연계)
-- ---------------------------------------------------------------------------
INSERT INTO DEV_AREA (DEV_AREA_CD, DEV_AREA_NM, SORT_ORD, USE_YN) VALUES ('DEV', '개발', 1, 'Y');
INSERT INTO DEV_AREA (DEV_AREA_CD, DEV_AREA_NM, SORT_ORD, USE_YN) VALUES ('QA',  '테스트', 2, 'Y');
INSERT INTO DEV_AREA (DEV_AREA_CD, DEV_AREA_NM, SORT_ORD, USE_YN) VALUES ('OPS', '운영', 3, 'Y');

-- ---------------------------------------------------------------------------
-- DEV 영역 — Rev 1 (이력, 최종 Rev 조회 시 제외)
-- ---------------------------------------------------------------------------
INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'CD', 'DEV', 1, 'CLOSED', 'DEV Rev 1 - CD 초기 등록', 'admin', '2025-11-01 09:00:00', 'admin', '2025-11-01 09:00:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'EU', 'DEV', 1, 'CLOSED', 'DEV Rev 1 - EU 초기 등록', 'admin', '2025-11-01 09:10:00', 'admin', '2025-11-01 09:10:00');

-- ---------------------------------------------------------------------------
-- DEV 영역 — Rev 2 (이력)
-- ---------------------------------------------------------------------------
INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'CD', 'DEV', 2, 'CLOSED', 'DEV Rev 2 - CD 용도 반영', 'kim.dev', '2026-01-10 14:20:00', 'kim.dev', '2026-01-10 14:20:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'EU', 'QA',  2, 'CLOSED', 'DEV Rev 2 - EU QA 전환', 'kim.dev', '2026-01-10 14:25:00', 'kim.dev', '2026-01-10 14:25:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'US', NULL,  2, 'CLOSED', 'DEV Rev 2 - US 용도 미지정', 'kim.dev', '2026-01-10 14:30:00', 'kim.dev', '2026-01-10 14:30:00');

-- ---------------------------------------------------------------------------
-- DEV 영역 — Rev 3 (최종 Rev, 그리드 조회 대상)
-- ---------------------------------------------------------------------------
INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'CD', 'DEV', 3, 'ACTIVE', 'DEV Rev 3 - CD 개발용 확정', 'park.rev', '2026-03-01 10:00:00', 'park.rev', '2026-03-15 16:40:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'EU', 'DEV', 3, 'ACTIVE', 'DEV Rev 3 - EU 개발용 확정', 'park.rev', '2026-03-01 10:05:00', 'park.rev', '2026-03-15 16:42:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'US', 'QA',  3, 'ACTIVE', 'DEV Rev 3 - US 테스트용 전환', 'park.rev', '2026-03-01 10:10:00', 'lee.qa', '2026-03-16 09:15:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'JP', NULL,  3, 'DRAFT',  'DEV Rev 3 - JP 검토 중', 'park.rev', '2026-03-01 10:15:00', 'park.rev', '2026-03-01 10:15:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'KR', 'QA',  3, 'ACTIVE', 'DEV Rev 3 - KR QA 반영', 'park.rev', '2026-03-01 10:20:00', 'lee.qa', '2026-03-17 11:00:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'CN', 'OPS', 3, 'ACTIVE', 'DEV Rev 3 - CN 운영 연계', 'park.rev', '2026-03-01 10:25:00', 'choi.ops', '2026-03-18 13:30:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'UK', 'DEV', 3, 'ACTIVE', 'DEV Rev 3 - UK 개발용', 'park.rev', '2026-03-01 10:30:00', 'park.rev', '2026-03-15 16:45:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('DEV', 'SG', 'DEV', 3, 'ACTIVE', 'DEV Rev 3 - SG 개발용', 'park.rev', '2026-03-01 10:35:00', 'park.rev', '2026-03-15 16:50:00');

-- ---------------------------------------------------------------------------
-- QA 영역 — Rev 1 (이력)
-- ---------------------------------------------------------------------------
INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'KR', 'QA', 1, 'CLOSED', 'QA Rev 1 - KR 테스트 초기', 'lee.qa', '2026-01-05 11:00:00', 'lee.qa', '2026-01-05 11:00:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'DE', 'QA', 1, 'CLOSED', 'QA Rev 1 - DE 테스트 초기', 'lee.qa', '2026-01-05 11:05:00', 'lee.qa', '2026-01-05 11:05:00');

-- ---------------------------------------------------------------------------
-- QA 영역 — Rev 2 (최종 Rev)
-- ---------------------------------------------------------------------------
INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'KR', 'QA', 2, 'ACTIVE', 'QA Rev 2 - KR 테스트 확정', 'lee.qa', '2026-02-20 09:00:00', 'lee.qa', '2026-03-10 15:20:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'DE', 'QA', 2, 'ACTIVE', 'QA Rev 2 - DE 테스트 확정', 'lee.qa', '2026-02-20 09:05:00', 'lee.qa', '2026-03-10 15:22:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'BR', 'QA', 2, 'ACTIVE', 'QA Rev 2 - BR 테스트 확정', 'lee.qa', '2026-02-20 09:10:00', 'jun.qa', '2026-03-11 10:00:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'FR', NULL, 2, 'DRAFT',  'QA Rev 2 - FR 검토 중', 'lee.qa', '2026-02-20 09:15:00', 'lee.qa', '2026-02-20 09:15:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'IN', NULL, 2, 'ACTIVE', 'QA Rev 2 - IN 테스트 반영', 'lee.qa', '2026-02-20 09:20:00', 'jun.qa', '2026-03-12 14:00:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('QA', 'MX', 'OPS', 2, 'ACTIVE', 'QA Rev 2 - MX OPS 연계 검증', 'lee.qa', '2026-02-20 09:25:00', 'jun.qa', '2026-03-13 16:30:00');

-- ---------------------------------------------------------------------------
-- OPS 영역 — Rev 1 (최종 Rev)
-- ---------------------------------------------------------------------------
INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('OPS', 'CN', 'OPS', 1, 'ACTIVE', 'OPS Rev 1 - CN 운영 확정', 'choi.ops', '2026-03-01 08:00:00', 'choi.ops', '2026-03-20 17:00:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('OPS', 'AU', 'OPS', 1, 'ACTIVE', 'OPS Rev 1 - AU 운영 확정', 'choi.ops', '2026-03-01 08:05:00', 'choi.ops', '2026-03-20 17:05:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('OPS', 'CA', 'OPS', 1, 'ACTIVE', 'OPS Rev 1 - CA 운영 확정', 'choi.ops', '2026-03-01 08:10:00', 'min.ops', '2026-03-21 09:00:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('OPS', 'MX', 'OPS', 1, 'ACTIVE', 'OPS Rev 1 - MX 운영 확정', 'choi.ops', '2026-03-01 08:15:00', 'min.ops', '2026-03-21 09:05:00');

INSERT INTO DEV_AREA_REV_INF (DEV_AREA_CD, OWNER_CD, USAGE_CD, FINAL_REV, REV_STATUS, REV_DESC, CREATE_USER, CREATE_DT, UPDATE_USER, UPDATE_DT)
VALUES ('OPS', 'SG', 'DEV', 1, 'DRAFT',  'OPS Rev 1 - SG DEV 연계 검토', 'choi.ops', '2026-03-01 08:20:00', 'choi.ops', '2026-03-01 08:20:00');

COMMIT;

-- ---------------------------------------------------------------------------
-- API 조회 참고 (백엔드 구현 시)
-- ---------------------------------------------------------------------------
-- 탭 목록:
--   SELECT DEV_AREA_CD AS devAreaCd, DEV_AREA_NM AS devAreaName
--   FROM DEV_AREA WHERE USE_YN = 'Y' ORDER BY SORT_ORD;
--
-- Rev 목록 API (GET /dev-area-rev?devAreaCd=):
--   DB에서 devAreaCd 전체 Rev 조회 후 서버에서 최종 Rev만 ownerCd별 usageList로 그룹
--   응답 예: [{ devAreaCd, ownerCd, finalRev, usageList: [{ usageCd, revStatus, ... }] }]
